name: Build and Analyze

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
          cache: 'maven'

      - name: Create .env file for tests
        run: |
          echo "EMAIL_USERNAME=${{ secrets.EMAIL_USERNAME }}" > .env
          echo "EMAIL_PASSWORD=${{ secrets.EMAIL_PASSWORD }}" >> .env

      - name: Build, Test & Coverage
        run: mvn -B verify --file pom.xml

      - name: SonarCloud Scan
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          args: >
            -Dsonar.projectKey=appointment123_s123
            -Dsonar.organization=appointment123-1
            -Dsonar.host.url=https://sonarcloud.io
            -Dsonar.java.binaries=target/classes
            -Dsonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
            -Dsonar.exclusions=**/presentation_Layer/**,**/doc/**,**/docs/**,**/target/**,**/target/site/**,**/GenerateHash.java
            -Dsonar.coverage.exclusions=**/src/test/java/**,**/presentation_Layer/**,**/presentation/**,**/connectDB/**,**/main/Main.java,**/service/ReminderService.java
            -Dsonar.cpd.exclusions=**/src/test/java/**,**/presentation_Layer/**,**/presentation/**,**/doc/**,**/GenerateHash.java
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
